ip: "25.145.82.0"
port: "5000"
proto: tcp
balancing_alg: random
retry_amount: 3
max_response_seconds: 60
max_clients_limit: 2000
max_idle_seconds: 300
servers:
  - address: "127.0.0.1:23769"
        
  - address: "127.0.0.1:23769"
    retry_amount: 1
    max_response_seconds: 60
        
  - address: "127.0.0.1:23769"
    retry_amount: 5
    max_response_seconds: 120
    max_clients_limit: 500
    max_idle_seconds: 10

# Несколько балансировщиков
ports:
  # Один балансировщик
  - 5000:
    proto: tcp
    balancing_alg: random
    retry_amount: 3
    max_response_seconds: 60
    max_clients_limit: 2000
    max_idle_seconds: 300
    servers:
      - address: "25.145.82.0:23769"
        retry_amount: 3
        max_response_seconds: 60
            
      - address: "25.145.83.0:23769"
        retry_amount: 1
        max_response_seconds: 60
            
      - address: "25.145.84.0:23769"
        retry_amount: 5
        max_response_seconds: 60
        max_idle_seconds: 10
        
  - 7222:
    proto: http
    balancing_alg: round robin
    retry_amount: 5
    max_response_seconds: 60
    max_clients_limit: 3000
    max_idle_seconds: 100
    servers:
      - address: "25.145.82.0:23769"
        retry_amount: 3
        max_response_seconds: 60
            
      - address: "25.145.83.0:23769"
        retry_amount: 1
        max_response_seconds: 60
    routes:
      - route: /orders
        servers:
          - address: "25.145.82.0:23769"
            max_response_seconds: 120
            dest_route: /order